---
# tasks file for apache
- name: Install Apache Server
  apt: name=apache2 state=latest update_cache=yes

- name: Install Java in apache
  apt: name=default-jdk state=latest 

- name: Use Custom Configuration file
  copy: src=apache2.conf dest=/etc/apache2/
  notify:
      - Restart Apache Service

- name: Use Custom Index.html file
  copy: src=index.html dest=/var/www/html/

- name: Start Apache Service
  service: name=apache2 state=started
